import type { BossDef } from './bossEngine';

/**
 * Los siete jefes del continente: animales reales llevados a la leyenda, con un toque
 * sobrenatural. Valores de daño en fracción de la salud del jugador (antes de su defensa).
 */
export const MATRIARCH: BossDef = {
  id: 'matriarch',
  name: 'La Matriarca',
  title: 'Reina del clan de la Luna Rota',
  model: 'hyena',
  scale: 2.1,
  tint: '#8c8098',
  glow: '#3b1a5c',
  eyes: '#c9a4ff',
  minAge: 2,
  strength: 1.45,
  damageTaken: 0.5,
  postureTaken: 0.65,
  speed: [4.5, 6],
  phase2At: 0.5,
  phase2Title: 'La luna se rompe',
  phase2Text: 'La Matriarca se alza entre sombras: ya no está sola en su cuerpo',
  attacks: [
    { kind: 'combo', weight: 3, maxDist: 4.6, windup: 0.65, damage: 0.075, hits: 3, interval: 0.42, guardCost: 0.22, telegraph: 'La Matriarca abre las fauces: tres dentelladas seguidas' },
    { kind: 'lunge', weight: 2, minDist: 4.6, maxDist: 18, windup: 0.9, damage: 0.16, speed: 15, guardCost: 0.5, stagger: 0.6, telegraph: 'Se agazapa entre los huesos… ¡va a embestir!' },
    { kind: 'aoe', weight: 1.4, phase: 2, windup: 1.35, damage: 0.15, radius: 11, unblockable: true, stagger: 0.8, eclipse: true, telegraph: 'Aúlla a la luna rota: esquiva en el último instante' },
    { kind: 'vanish', weight: 1.3, phase: 2, windup: 0.7, damage: 0.11, guardCost: 0.3, telegraph: 'Se disuelve en sombra… mira a tu espalda' },
  ],
  summons: [
    { at: 0.75, count: 2, model: 'hyena', name: 'Hiena espectral', strength: 0.5, damageTaken: 1.6, spectral: true },
    { at: 0.35, count: 3, model: 'hyena', name: 'Hiena espectral', strength: 0.5, damageTaken: 1.6, spectral: true },
  ],
  relic: 'matriarchTooth',
  essence: 2500,
  den: { id: 'cemetery', name: 'Guarida del Cementerio' },
  intro: 'Reina del clan de la Luna Rota. Los huesos de este claro son de quienes la desafiaron.',
  victory: 'Venciste a La Matriarca, reina del clan de la Luna Rota. Su diente es ahora tuyo y el delta queda abierto',
  arenaRadius: 30,
};

export const CROCODILE: BossDef = {
  id: 'crocodile',
  name: 'El Señor del Delta',
  title: 'Cocodrilo milenario del Okavango',
  model: 'croc',
  scale: 2.4,
  tint: '#4d5a3a',
  glow: '#15302a',
  eyes: '#e8d36a',
  minAge: 3,
  strength: 1.8,
  damageTaken: 0.42,
  postureTaken: 0.55,
  speed: [3.2, 4.4],
  phase2At: 0.5,
  phase2Title: 'Las aguas suben',
  phase2Text: 'El delta entero parece respirar con él: ahora ataca desde el agua',
  attacks: [
    { kind: 'combo', weight: 2.5, maxDist: 5, windup: 0.85, damage: 0.12, hits: 2, interval: 0.6, guardCost: 0.35, telegraph: 'Abre las mandíbulas despacio… luego las cierra de golpe dos veces' },
    { kind: 'lunge', weight: 2, minDist: 4, maxDist: 14, windup: 1.1, damage: 0.2, speed: 13, guardCost: 0.6, stagger: 1, telegraph: 'Se queda inmóvil como un tronco: va a lanzarse' },
    { kind: 'submerge', weight: 1.6, phase: 2, windup: 0.9, damage: 0.22, stagger: 1.2, guardCost: 0.6, telegraph: 'Se hunde en el barro… ¡saldrá delante de ti!' },
    { kind: 'aoe', weight: 1, phase: 2, windup: 1.1, damage: 0.13, radius: 7, unblockable: true, stagger: 0.7, telegraph: 'Golpea el barro con la cola: esquiva la ola' },
  ],
  summons: [],
  relic: 'deltaScale',
  essence: 4000,
  den: { id: 'delta-boss', name: 'Guarida de la Isla' },
  intro: 'Más viejo que los baobabs. Las aguas del delta llevan su nombre.',
  victory: 'El Señor del Delta se hunde por última vez. El camino al Kalahari queda abierto',
  arenaRadius: 32,
};

export const SHADOW_LION: BossDef = {
  id: 'shadowLion',
  name: 'La Sombra del Kalahari',
  title: 'León de melena negra',
  model: 'lion',
  scale: 1.35,
  mane: 1,
  tint: '#3a2a22',
  glow: '#2a1208',
  eyes: '#ff9b4a',
  minAge: 3.5,
  strength: 1.7,
  damageTaken: 0.5,
  postureTaken: 0.6,
  speed: [5, 6.5],
  phase2At: 0.5,
  phase2Title: 'Arena y sombra',
  phase2Text: 'La Sombra pelea como tú: esquiva, ruge y no deja de rodearte',
  attacks: [
    { kind: 'combo', weight: 3, maxDist: 4.5, windup: 0.5, damage: 0.08, hits: 4, interval: 0.32, guardCost: 0.18, telegraph: 'Encadena zarpazos como tú: cuatro golpes seguidos' },
    { kind: 'lunge', weight: 2, minDist: 4, maxDist: 16, windup: 0.75, damage: 0.15, speed: 17, guardCost: 0.45, stagger: 0.5, telegraph: 'Se agazapa: embestida' },
    { kind: 'aoe', weight: 1.2, phase: 2, windup: 1.0, damage: 0.12, radius: 9, unblockable: true, stagger: 1, telegraph: 'Rugido aturdidor: esquívalo en el último instante' },
    { kind: 'vanish', weight: 1, phase: 2, windup: 0.6, damage: 0.12, guardCost: 0.3, telegraph: 'Desaparece entre la arena levantada…' },
  ],
  summons: [{ at: 0.4, count: 2, model: 'lion', name: 'Leona de sombra', strength: 0.7, damageTaken: 1.4, spectral: true }],
  relic: 'shadowMane',
  essence: 5500,
  den: { id: 'kalahari-boss', name: 'Guarida de la Sombra' },
  intro: 'Dicen que es tu reflejo en el desierto. Pelea igual que tú.',
  victory: 'La Sombra del Kalahari se deshace en arena. La selva del Congo te espera',
  arenaRadius: 30,
};

export const LEOPARD: BossDef = {
  id: 'leopard',
  name: 'El Fantasma',
  title: 'Leopardo de la selva',
  model: 'leopard',
  scale: 1.15,
  female: true,
  tint: '#c99a4e',
  glow: '#1b2a12',
  eyes: '#b7ff7a',
  minAge: 4,
  strength: 1.5,
  damageTaken: 0.62,
  postureTaken: 0.7,
  speed: [6.5, 8],
  phase2At: 0.5,
  phase2Title: 'Ojos en los árboles',
  phase2Text: 'El Fantasma deja de esconderse: ahora caza de verdad',
  attacks: [
    { kind: 'combo', weight: 2.5, maxDist: 4, windup: 0.4, damage: 0.07, hits: 3, interval: 0.26, guardCost: 0.16, telegraph: 'Zarpazos rapidísimos: bloquea o esquiva hacia atrás' },
    { kind: 'vanish', weight: 2.5, windup: 0.6, damage: 0.14, guardCost: 0.35, telegraph: 'Desaparece en el follaje… cae desde atrás' },
    { kind: 'lunge', weight: 1.5, minDist: 4, maxDist: 18, windup: 0.6, damage: 0.15, speed: 19, guardCost: 0.45, stagger: 0.5, telegraph: 'Un salto desde lejos: esquiva hacia un lado' },
  ],
  summons: [],
  nightOnly: true,
  relic: 'ghostEye',
  essence: 7000,
  den: { id: 'congo-boss', name: 'Guarida del Fantasma' },
  intro: 'Nadie lo ha visto de día. Esta noche te ha elegido a ti.',
  victory: 'El Fantasma por fin se deja ver… al caer. Los montes Rwenzori se abren',
  arenaRadius: 28,
};

export const BUFFALO: BossDef = {
  id: 'buffalo',
  name: 'El Guardián de la Niebla',
  title: 'Búfalo colosal de los montes',
  model: 'buffalo',
  scale: 2.2,
  tint: '#2c2622',
  glow: '#2a3440',
  eyes: '#bfe3ff',
  minAge: 4.5,
  strength: 2.1,
  damageTaken: 0.4,
  postureTaken: 0.5,
  speed: [3.5, 4.8],
  phase2At: 0.45,
  phase2Title: 'Tormenta en la montaña',
  phase2Text: 'El Guardián se enfurece: sus cargas ya no se detienen',
  attacks: [
    { kind: 'charge', weight: 3, minDist: 5, maxDist: 30, windup: 1.2, damage: 0.24, speed: 16, duration: 1.4, guardCost: 0.8, stagger: 1.2, telegraph: 'Escarba la tierra: una carga que no se puede bloquear bien. Esquiva y déjalo estrellarse' },
    { kind: 'combo', weight: 2, maxDist: 5, windup: 0.8, damage: 0.12, hits: 2, interval: 0.55, guardCost: 0.4, telegraph: 'Cornadas a un lado y a otro' },
    { kind: 'aoe', weight: 1.2, phase: 2, windup: 1.2, damage: 0.16, radius: 8, unblockable: true, stagger: 1, telegraph: 'Se alza sobre las patas traseras: el suelo va a temblar' },
  ],
  summons: [{ at: 0.3, count: 2, model: 'buffalo', name: 'Búfalo de niebla', strength: 0.8, damageTaken: 1.2, spectral: true }],
  relic: 'guardianHorn',
  essence: 9000,
  den: { id: 'mountains-boss', name: 'Guarida del Guardián' },
  intro: 'La niebla tiene cuernos. Y ahora te ha visto.',
  victory: 'El Guardián de la Niebla cae y la montaña calla. El cráter del Ngorongoro se abre',
  arenaRadius: 34,
};

export const KINGS: BossDef = {
  id: 'kings',
  name: 'El Rey de Reyes',
  title: 'Coalición de tres hermanos',
  model: 'lion',
  scale: 1.5,
  mane: 0.7,
  tint: '#a77a3a',
  glow: '#5a3a08',
  eyes: '#ffd36a',
  minAge: 5,
  strength: 2.1,
  damageTaken: 0.4,
  postureTaken: 0.5,
  speed: [5, 6.5],
  phase2At: 0.5,
  phase2Title: 'El rey herido',
  phase2Text: 'Sin sus hermanos, el rey pelea con todo su orgullo',
  attacks: [
    { kind: 'combo', weight: 3, maxDist: 4.6, windup: 0.55, damage: 0.1, hits: 3, interval: 0.36, guardCost: 0.25, telegraph: 'El rey encadena zarpazos con todo su peso' },
    { kind: 'lunge', weight: 2, minDist: 4, maxDist: 16, windup: 0.8, damage: 0.18, speed: 16, guardCost: 0.5, stagger: 0.7, telegraph: 'Embestida del rey' },
    { kind: 'aoe', weight: 1.3, phase: 2, windup: 1.1, damage: 0.17, radius: 11, unblockable: true, stagger: 1, eclipse: true, telegraph: 'El rugido del trono: esquiva en el último instante' },
    { kind: 'vanish', weight: 0.8, phase: 2, windup: 0.6, damage: 0.13, guardCost: 0.35, telegraph: 'El polvo del cráter lo oculta…' },
  ],
  summons: [{ at: 1, count: 2, model: 'lion', name: 'Hermano del rey', strength: 1.2, damageTaken: 0.9 }],
  relic: 'kingsCrown',
  essence: 15000,
  den: { id: 'crater-boss', name: 'Guarida del Trono' },
  intro: 'Tres hermanos que nunca han perdido. El trono del cráter es suyo desde hace cien años.',
  victory: 'El Rey de Reyes ha caído. Eres el rey de todo el continente',
  arenaRadius: 34,
};

export const SEA_LIONESS: BossDef = {
  id: 'seaLioness',
  name: 'La Leona del Mar',
  title: 'Cazadora de la costa olvidada',
  model: 'lion',
  scale: 1.25,
  female: true,
  tint: '#b7c2c7',
  glow: '#1c4a5c',
  eyes: '#8ff3ff',
  minAge: 5,
  strength: 2.0,
  damageTaken: 0.45,
  postureTaken: 0.55,
  speed: [6, 7.5],
  phase2At: 0.5,
  phase2Title: 'Pleamar',
  phase2Text: 'La marea sube con ella',
  attacks: [
    { kind: 'combo', weight: 3, maxDist: 4.4, windup: 0.45, damage: 0.09, hits: 4, interval: 0.3, guardCost: 0.2, telegraph: 'Golpes rápidos como olas' },
    { kind: 'lunge', weight: 2, minDist: 4, maxDist: 18, windup: 0.6, damage: 0.17, speed: 18, guardCost: 0.45, stagger: 0.6, telegraph: 'Salta desde la niebla' },
    { kind: 'submerge', weight: 1.4, phase: 2, windup: 0.8, damage: 0.18, stagger: 0.9, guardCost: 0.5, telegraph: 'Se funde con la niebla del mar…' },
    { kind: 'aoe', weight: 1.2, phase: 2, windup: 1.2, damage: 0.16, radius: 10, unblockable: true, stagger: 0.9, eclipse: true, telegraph: 'Ruge como la marea: esquiva' },
  ],
  summons: [],
  nightOnly: false,
  relic: 'seaPearl',
  essence: 20000,
  den: { id: 'coast-boss', name: 'Guarida de los Naufragios' },
  intro: 'Caza focas entre la niebla y la marea. Nadie ha vuelto de esta costa.',
  victory: 'La Leona del Mar te reconoce. Ya no queda ninguna leyenda en el continente que no sea la tuya',
  arenaRadius: 30,
};

/** Jefe de cada región (la sabana tiene a La Matriarca). */
export const REGION_BOSSES: Record<string, BossDef> = {
  delta: CROCODILE,
  kalahari: SHADOW_LION,
  congo: LEOPARD,
  mountains: BUFFALO,
  crater: KINGS,
  coast: SEA_LIONESS,
};
